### ISSUE TITLE
how can get the status code string 

### ISSUE THREAD

**Issue by aengusjiang** [nodejs/llhttp#172] opened 2022-08-04 07:10 UTC

**Comment by aengusjiang** [comment] 2022-08-04 07:13
for the old repo http_parse has a method to get the status code string which named http_status_str.
How about add the similar method  in this repo such as llhttp_status_str

**Comment by pallas** [comment] 2022-08-08 22:48
Since you might receive the status in different chunks, you need to implement the `on_status` and `on_status_complete` callbacks to store the string yourself. The library doesn't allocate memory on its own.

**Comment by aengusjiang** [comment] 2022-08-09 05:46
No. I mean that convert int status to string.
the http_parser.h line 421 in http_pasrer lib have the convert method， just a map.
https://github.com/nodejs/http-parser/blob/main/http_parser.h

**Comment by ShogunPanda** [comment] 2022-08-22 14:41
Duplicate of https://github.com/nodejs/llhttp/issues/106

**Closed by ShogunPanda** 2022-08-22 14:41 UTC
