### ISSUE TITLE
Does llhttp have the function of parsing http field, like ’http_parser_parse_url‘ of http_parser.

### ISSUE THREAD

**Issue by ldcsaa** [nodejs/llhttp#53] opened 2020-03-19 09:26 UTC
http_parser has function _int http_parser_parse_url()_ to parse url fields.
does llhttp can provide a similar function ?

**Comment by indutny** [comment] 2020-07-08 17:10
Duplicate of https://github.com/nodejs/llhttp/issues/7

**Closed by indutny** 2020-07-08 17:10 UTC
