### ISSUE TITLE
Ignores unsupported Transfer-Encoding values

### ISSUE THREAD

**Issue by mattiasgrenfeldt** [nodejs/llhttp#120] opened 2021-06-20 09:55 UTC
`llhttp` only seems to support the `chunked` transfer coding. But it ignores all other unsupported ones. 

If a request like this is sent to Node:

```
GET / HTTP/1.1
Host: localhost:8080
Transfer-Encoding: JUNK, chunked

5
hello
0

```
Then the request is interpreted as chunked. Here `JUNK` is simply ignored.

According to RFC 7230:

```
   A server that receives a request message with a transfer coding it
   does not understand SHOULD respond with 501 (Not Implemented).
```
Source: last paragraph of https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.1

(Found by Mattias Grenfeldt and Asta Olofsson)

**Comment by indutny** [comment] 2021-06-21 04:52
Thanks for reporting this!

This sounds like a documentation bug because even though llhttp doesn't support any transfer-encoding but `chunked`, the app that uses it might support the other ones! Furthermore, if you just proxy requests, but parse them for routing purposes - you don't have to handle any other transfer-encoding, but `chunked`.

I'm going to close it since this has to be implemented in the user code by design. Feel free to open a PR for adding this to the documentation.

**Closed by indutny** 2021-06-21 04:52 UTC
