### ISSUE TITLE
add some http request methods support

### ISSUE THREAD

**Issue by masx200** [nodejs/llhttp#61] opened 2020-06-08 14:03 UTC
Check the request methods supported by the http1 module.
```js
console.log(http.METHODS);
```
```json
[
  "ACL",
  "BIND",
  "CHECKOUT",
  "CONNECT",
  "COPY",
  "DELETE",
  "GET",
  "HEAD",
  "LINK",
  "LOCK",
  "M-SEARCH",
  "MERGE",
  "MKACTIVITY",
  "MKCALENDAR",
  "MKCOL",
  "MOVE",
  "NOTIFY",
  "OPTIONS",
  "PATCH",
  "POST",
  "PROPFIND",
  "PROPPATCH",
  "PURGE",
  "PUT",
  "REBIND",
  "REPORT",
  "SEARCH",
  "SOURCE",
  "SUBSCRIBE",
  "TRACE",
  "UNBIND",
  "UNLINK",
  "UNLOCK",
  "UNSUBSCRIBE"
]
```
The HTTP1 module does not support the following request methods.
```json
[
  "BASELINE-CONTROL",
  "CHECKIN",
  "LABEL",
  "MKREDIRECTREF",
  "MKWORKSPACE",
  "ORDERPATCH",
  "PRI",
  "UNCHECKOUT",
  "UPDATE",
  "UPDATEREDIRECTREF",
  "VERSION-CONTROL"
]
```

https://github.com/nodejs/node/issues/33699

**Comment by indutny** [comment] 2020-07-08 17:11
Duplicate of https://github.com/nodejs/llhttp/issues/11

**Closed by indutny** 2020-07-08 17:11 UTC
